In [1]:
import pandas as pd

In [2]:
reviews = pd.read_csv('../src/reviews.csv')

reviews.head(5)

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,27934,1094339,2012-04-07,1368195,Michael,We stayed in the apartment for a week and we e...
1,27934,1241042,2012-05-07,2007324,Scott,My girlfriend and I recently stayed in Nuttee'...
2,27934,1523384,2012-06-20,2263352,Marc,I stayed for one month at the condo and was re...
3,27934,1655571,2012-07-08,558987,Leyla,Nuttee was a great host! I really enjoyed her ...
4,27934,1972192,2012-08-13,2359865,Rachel,Nuttee was an amazing host. She and her daught...

In [4]:
listings = pd.read_csv('../src/listings.csv')

listings.head(5)

/tmp/ipykernel_19301/1269933750.py:1: DtypeWarning: Columns (68) have mixed types. Specify dtype option on import or set low_memory=False.
  listings = pd.read_csv('../src/listings.csv')

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,27934,https://www.airbnb.com/rooms/27934,20240626142103,2024-06-27,city scrape,Nice room with superb city view,Our cool and comfortable one bedroom apartment...,It is very center of Bangkok and easy access t...,https://a0.muscache.com/pictures/566374/23157b...,120437,...,4.91,4.66,4.75,NaN,f,2,2,0,0,0.43
1,27979,https://www.airbnb.com/rooms/27979,20240626142103,2024-06-27,previous scrape,"Easy going landlord,easy place",NaN,NaN,https://a0.muscache.com/pictures/106247594/1d6...,120541,...,NaN,NaN,NaN,NaN,f,2,1,1,0,NaN
2,28745,https://www.airbnb.com/rooms/28745,20240626142103,2024-06-27,previous scrape,modern-style apartment in Bangkok,A modern-style apartment situated in a cool ne...,Ramkumheang neigbourhood - hip place with food...,https://a0.muscache.com/pictures/160369/92a7ec...,123784,...,NaN,NaN,NaN,NaN,f,1,0,1,0,NaN
3,55681,https://www.airbnb.com/rooms/55681,20240626142103,2024-06-27,city scrape,Sathorn Terrace Apartment(61),NaN,NaN,https://a0.muscache.com/pictures/71205c61-1553...,263049,...,4.88,4.76,4.84,NaN,f,7,0,3,0,0.21
4,35780,https://www.airbnb.com/rooms/35780,20240626142103,2024-06-27,city scrape,Spacious one bedroom at The Kris Condo Bldg. 3,Cozy and clean apartment at MRT Sutthisarn sta...,"There is McDonald's, Au bon Pain and Max Value...",https://a0.muscache.com/pictures/89302e4b-b529...,153730,...,4.83,4.83,5.00,NaN,f,1,0,1,0,0.06

In [5]:
listings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23651 entries, 0 to 23650
Data columns (total 75 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            23651 non-null  int64
 1   listing_url                                   23651 non-null  object
 2   scrape_id                                     23651 non-null  int64
 3   last_scraped                                  23651 non-null  object
 4   source                                        23651 non-null  object
 5   name                                          23651 non-null  object
 6   description                                   22820 non-null  object
 7   neighborhood_overview                         10195 non-null  object
 8   picture_url                                   23651 non-null  object
 9   host_id                                       23651 non-null  int64
 10  host_url                                      23651 non-null  object
 11  host_name                                     23650 non-null  object
 12  host_since                                    23651 non-null  object
 13  host_location                                 17797 non-null  object
 14  host_about                                    13555 non-null  object
 15  host_response_time                            18929 non-null  object
 16  host_response_rate                            18929 non-null  object
 17  host_acceptance_rate                          19392 non-null  object
 18  host_is_superhost                             22650 non-null  object
 19  host_thumbnail_url                            23651 non-null  object
 20  host_picture_url                              23651 non-null  object
 21  host_neighbourhood                            9736 non-null   object
 22  host_listings_count                           23651 non-null  int64
 23  host_total_listings_count                     23651 non-null  int64
 24  host_verifications                            23651 non-null  object
 25  host_has_profile_pic                          23651 non-null  object
 26  host_identity_verified                        23651 non-null  object
 27  neighbourhood                                 10195 non-null  object
 28  neighbourhood_cleansed                        23651 non-null  object
 29  neighbourhood_group_cleansed                  0 non-null      float64
 30  latitude                                      23651 non-null  float64
 31  longitude                                     23651 non-null  float64
 32  property_type                                 23651 non-null  object
 33  room_type                                     23651 non-null  object
 34  accommodates                                  23651 non-null  int64
 35  bathrooms                                     19009 non-null  float64
 36  bathrooms_text                                23526 non-null  object
 37  bedrooms                                      22403 non-null  float64
 38  beds                                          18973 non-null  float64
 39  amenities                                     23651 non-null  object
 40  price                                         19012 non-null  object
 41  minimum_nights                                23651 non-null  int64
 42  maximum_nights                                23651 non-null  int64
 43  minimum_minimum_nights                        23651 non-null  int64
 44  maximum_minimum_nights                        23651 non-null  int64
 45  minimum_maximum_nights                        23651 non-null  int64
 46  maximum_maximum_nights                        23651 non-null  int64
 47  minimum_nights_avg_ntm                        23651 non-null  float64
 48  maximum_nights_avg_ntm                        23651 non-null  float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              21405 non-null  object
 51  availability_30                               23651 non-null  int64
 52  availability_60                               23651 non-null  int64
 53  availability_90                               23651 non-null  int64
 54  availability_365                              23651 non-null  int64
 55  calendar_last_scraped                         23651 non-null  object
 56  number_of_reviews                             23651 non-null  int64
 57  number_of_reviews_ltm                         23651 non-null  int64
 58  number_of_reviews_l30d                        23651 non-null  int64
 59  first_review                                  15428 non-null  object
 60  last_review                                   15428 non-null  object
 61  review_scores_rating                          15428 non-null  float64
 62  review_scores_accuracy                        15406 non-null  float64
 63  review_scores_cleanliness                     15405 non-null  float64
 64  review_scores_checkin                         15401 non-null  float64
 65  review_scores_communication                   15405 non-null  float64
 66  review_scores_location                        15400 non-null  float64
 67  review_scores_value                           15399 non-null  float64
 68  license                                       1 non-null      object
 69  instant_bookable                              23651 non-null  object
 70  calculated_host_listings_count                23651 non-null  int64
 71  calculated_host_listings_count_entire_homes   23651 non-null  int64
 72  calculated_host_listings_count_private_rooms  23651 non-null  int64
 73  calculated_host_listings_count_shared_rooms   23651 non-null  int64
 74  reviews_per_month                             15428 non-null  float64
dtypes: float64(17), int64(23), object(35)
memory usage: 13.5+ MB

In [7]:
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 438958 entries, 0 to 438957
Data columns (total 6 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   listing_id     438958 non-null  int64
 1   id             438958 non-null  int64
 2   date           438958 non-null  object
 3   reviewer_id    438958 non-null  int64
 4   reviewer_name  438953 non-null  object
 5   comments       438901 non-null  object
dtypes: int64(3), object(3)
memory usage: 20.1+ MB